version: '3.7'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  node-app:
    container_name: node-app
    image: ghcr.io/stefan-aradjanin/stefan-aradjanin/docker-nodejs-sample:v1.0.6
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    #   target: prod
    # volumes:
    #   - ./src:/app/src
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=stefandb
      - POSTGRES_USER=stefanuser
      - POSTGRES_PASSWORD=stefanpassword
    restart: unless-stopped
    links:
      - db
    depends_on:
      - db
    #command: npm run dev



   
    

