apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_PORT: "{{ .Values.postgres_config.port }}"
  POSTGRES_HOST: {{ .Values.postgres_config.host }}