apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_DB: {{ .Values.postgres_config.db }}
  POSTGRES_USER: {{ .Values.postgres_config.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres_config.password }}
  POSTGRES_PORT: "{{ .Values.postgres_config.port }}"
  POSTGRES_HOST: {{ .Values.postgres_config.host }}