apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
stringData:
  POSTGRES_DB: {{ .Values.secrets_config.db }}
  POSTGRES_USER: {{ .Values.secrets_config.user }}
  POSTGRES_PASSWORD: {{ .Values.secrets_config.password }}