name: Build and push Docker Image to GitHub Container Registry

on:
#for manual trigger, will be change
 # workflow_dispatch:

 #for automatic trigger on version change
  push:
    tags:
      - 'v*.*.*'

jobs:
  push_to_registry:
    name: Push Docker image to registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get version tag
      id: get_tag
      #extract the last part of the GITHUB_REF
      #the output from echo is redirected to the GITHUB_ENV file
      run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        # tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
        tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{env.TAG}}
      
   
